#!/usr/bin/env python3
"""patch_arms.py <run>[:<bridge_url>] ... — for a run generated by make_snowball_grpo.py (cloned from the pre-#141 template):
apply OT-Agent #141 (USR1@300 shutdown warning + rl_shutdown.sh helper) to the sbatch, enable the launcher's artifact store
(one sparse ext4 image per run, trials inside the mount), and optionally pin APPTAINER_BRIDGE_URL. Idempotent per marker checks.
2026-09-04 session 20ae8169."""
import json, sys
sys.path.insert(0, "/e/project1/transfernetx/lee27/code/OpenThoughts-Agent")
from pathlib import Path
from hpc.artifact_store import ensure_image, paths_for_run

E = "/e/fscratch/reformo/lee27/experiments"
OLD_FT = '''forward_termination() {
  echo "Received SIGTERM; forwarding it to the RL runner"
  if [[ -n "$RL_RUNNER_PID" ]] && kill -0 "$RL_RUNNER_PID" 2>/dev/null; then
    kill -TERM "$RL_RUNNER_PID"
  else
    exit 143
  fi
}
'''
NEW_FT = '''source "$WORKDIR/hpc/shell_utils/rl_shutdown.sh"

forward_termination() {
  echo "Received Slurm shutdown signal; forwarding SIGTERM to the RL runner"
  if ! forward_termination_to_rl_runner "$RL_RUNNER_PID"; then
    exit 143
  fi
}
'''
for spec in sys.argv[1:]:
    R, _, bridge = spec.partition(":http")
    bridge = "http" + bridge if bridge else None
    sp = f"{E}/{R}/sbatch/{R}_rl.sbatch"; cp = f"{E}/{R}/configs/{R}_rl_config.json"
    s = open(sp).read()
    if "#SBATCH --signal=B:USR1@300" not in s:
        assert s.count("#SBATCH --signal=B:TERM@180") == 1; s = s.replace("#SBATCH --signal=B:TERM@180", "#SBATCH --signal=B:USR1@300")
        assert s.count("  trap - EXIT TERM\n") == 1; s = s.replace("  trap - EXIT TERM\n", "  trap - EXIT TERM USR1\n")
        assert s.count(OLD_FT) == 1; s = s.replace(OLD_FT, NEW_FT)
        assert s.count("trap forward_termination TERM\n") == 1; s = s.replace("trap forward_termination TERM\n", "trap forward_termination TERM USR1\n")
        print(R, "#141 applied")
    run_dir = Path(f"{E}/{R}/{R}"); run_dir.mkdir(parents=True, exist_ok=True)
    p = paths_for_run(run_dir); ensure_image(p.image, size="1T", inode_count=50_000_000)
    if 'ARTIFACT_STORE_ENABLED="0"' in s:
        assert s.count('ARTIFACT_STORE_IMAGE=""') == 1 and s.count('ARTIFACT_STORE_MOUNT=""') == 1
        s = (s.replace('ARTIFACT_STORE_ENABLED="0"', 'ARTIFACT_STORE_ENABLED="1"')
              .replace('ARTIFACT_STORE_IMAGE=""', f'ARTIFACT_STORE_IMAGE="{p.image}"')
              .replace('ARTIFACT_STORE_MOUNT=""', f'ARTIFACT_STORE_MOUNT="{p.mount}"'))
        print(R, "artifact store enabled")
    if bridge and "export APPTAINER_BRIDGE_URL=" not in s:
        anchor = "export HARBOR_TMUX_BATCH_EXEC_TIMEOUT_MARGIN_SEC=600\n"; assert s.count(anchor) == 1
        s = s.replace(anchor, anchor + f"export APPTAINER_BRIDGE_URL={bridge}\n"); print(R, "bridge pinned", bridge)
    open(sp, "w").write(s)
    c = json.load(open(cp)); a = c["skyrl_hydra_args"]; trials = str(p.trials)
    i = [k for k, x in enumerate(a) if x.startswith("++terminal_bench_config.trials_dir=")]; assert len(i) == 1
    a[i[0]] = f"++terminal_bench_config.trials_dir={trials}"
    c["trials_dir"] = trials; c["artifact_store_enabled"] = True; c["artifact_store_image"] = str(p.image); c["artifact_store_mount"] = str(p.mount)
    json.dump(c, open(cp, "w"), indent=2)
    print(R, "image", p.image, "apparent", p.image.stat().st_size // 2**30, "GiB; mount", p.mount, "; trials", trials, "; bridge", bridge or "default")
