data:
  train_weights:
    ota10k: 1.0
  tokenizer: /e/fscratch/reformo/lee27/hf_hub/models--Qwen--Qwen3-30B-A3B-Base/snapshots/1b75feb79f60b8dc6c5bc769a898c206a1c6a4f9
  cache_dir: /e/fscratch/reformo/lee27/data/ota10k_levanter_cache
  shuffle:
    io_block_size: 256
    window_blocks: 512
    perm_type: feistel
  components:
    ota10k:
      format:
        type: chat
        messages_field: conversations
        chat_template: |
          {%- if tools %}
              {{- '<|im_start|>system\n' }}
              {%- if messages[0].role == 'system' %}
                  {{- messages[0].content + '\n\n' }}
              {%- endif %}
              {{- "# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
              {%- for tool in tools %}
                  {{- "\n" }}
                  {{- tool | tojson }}
              {%- endfor %}
              {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
          {%- else %}
              {%- if messages[0].role == 'system' %}
                  {{- '<|im_start|>system\n' + messages[0].content + '<|im_end|>\n' }}
              {%- endif %}
          {%- endif %}
          {%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}
          {%- for message in messages[::-1] %}
              {%- set index = (messages|length - 1) - loop.index0 %}
              {%- if ns.multi_step_tool and message.role == "user" and message.content is string and not(message.content.startswith('<tool_response>') and message.content.endswith('</tool_response>')) %}
                  {%- set ns.multi_step_tool = false %}
                  {%- set ns.last_query_index = index %}
              {%- endif %}
          {%- endfor %}
          {%- for message in messages %}
              {%- if message.content is string %}
                  {%- set content = message.content %}
              {%- else %}
                  {%- set content = '' %}
              {%- endif %}
              {%- if (message.role == "user") or (message.role == "system" and not loop.first) %}
                  {{- '<|im_start|>' + message.role + '\n' + content + '<|im_end|>' + '\n' }}
              {%- elif message.role == "assistant" %}
                  {%- set reasoning_content = '' %}
                  {%- if message.reasoning_content is string %}
                      {%- set reasoning_content = message.reasoning_content %}
                  {%- else %}
                      {%- if '</think>' in content %}
                          {%- set reasoning_content = content.split('</think>')[0].rstrip('\n').split('<think>')[-1].lstrip('\n') %}
                          {%- set content = content.split('</think>')[-1].lstrip('\n') %}
                      {%- endif %}
                  {%- endif %}
                  {%- if loop.index0 > ns.last_query_index and (loop.last or (not loop.last and reasoning_content)) %}
                      {{- '<|im_start|>' + message.role + '\n<think>' }}{% generation %}{{- '\n' + reasoning_content.strip('\n') + '\n</think>\n\n' + content.lstrip('\n') }}
                      {%- if message.tool_calls %}
                          {%- for tool_call in message.tool_calls %}
                              {%- if (loop.first and content) or (not loop.first) %}
                                  {{- '\n' }}
                              {%- endif %}
                              {%- if tool_call.function %}
                                  {%- set tool_call = tool_call.function %}
                              {%- endif %}
                              {{- '<tool_call>\n{"name": "' }}
                              {{- tool_call.name }}
                              {{- '", "arguments": ' }}
                              {%- if tool_call.arguments is string %}
                                  {{- tool_call.arguments }}
                              {%- else %}
                                  {{- tool_call.arguments | tojson }}
                              {%- endif %}
                              {{- '}\n</tool_call>' }}
                          {%- endfor %}
                      {%- endif %}
                      {{- '<|im_end|>' }}{% endgeneration %}{{- '\n' }}
                  {%- else %}
                      {{- '<|im_start|>' + message.role + '\n' }}{% generation %}{{- content }}
                      {%- if message.tool_calls %}
                          {%- for tool_call in message.tool_calls %}
                              {%- if (loop.first and content) or (not loop.first) %}
                                  {{- '\n' }}
                              {%- endif %}
                              {%- if tool_call.function %}
                                  {%- set tool_call = tool_call.function %}
                              {%- endif %}
                              {{- '<tool_call>\n{"name": "' }}
                              {{- tool_call.name }}
                              {{- '", "arguments": ' }}
                              {%- if tool_call.arguments is string %}
                                  {{- tool_call.arguments }}
                              {%- else %}
                                  {{- tool_call.arguments | tojson }}
                              {%- endif %}
                              {{- '}\n</tool_call>' }}
                          {%- endfor %}
                      {%- endif %}
                      {{- '<|im_end|>' }}{% endgeneration %}{{- '\n' }}
                  {%- endif %}
              {%- elif message.role == "tool" %}
                  {%- if loop.first or (messages[loop.index0 - 1].role != "tool") %}
                      {{- '<|im_start|>user' }}
                  {%- endif %}
                  {{- '\n<tool_response>\n' }}
                  {{- content }}
                  {{- '\n</tool_response>' }}
                  {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
                      {{- '<|im_end|>\n' }}
                  {%- endif %}
              {%- endif %}
          {%- endfor %}
          {%- if add_generation_prompt %}
              {{- '<|im_start|>assistant\n<think>\n' }}
          {%- endif %}
      source:
        type: url
        train_urls:
          - /e/fscratch/reformo/lee27/data/ota10k_jsonl/train.jsonl
model:
  type: qwen3_moe
  reference_checkpoint: /e/fscratch/reformo/lee27/hf_hub/models--Qwen--Qwen3-30B-A3B-Base/snapshots/1b75feb79f60b8dc6c5bc769a898c206a1c6a4f9
  tokenizer: /e/fscratch/reformo/lee27/hf_hub/models--Qwen--Qwen3-30B-A3B-Base/snapshots/1b75feb79f60b8dc6c5bc769a898c206a1c6a4f9
train_seq_len: 32768
trainer:
  seed: 42
  tracker:
    type: wandb
    project: jupiter-ota10k-sft
    name: ota10k_sft_qwen3_30b_a3b_base_levanter
  mp: p=f32,c=bfloat16
  train_batch_size: 96
  num_train_steps: 328
  checkpointer:
    base_path: /e/fscratch/reformo/lee27/checkpoints/ota10k_sft_30ba3b_levanter/ckpt
    keep:
      - every: 100
optimizer:
  learning_rate: 4e-5
  beta1: 0.9
  beta2: 0.98
  epsilon: 1e-8
  max_grad_norm: 1e-4
  weight_decay: 0.0
  lr_schedule: cosine
  warmup: 0.1
  min_lr_ratio: 0.0
initialize_from_hf: /e/fscratch/reformo/lee27/hf_hub/models--Qwen--Qwen3-30B-A3B-Base/snapshots/1b75feb79f60b8dc6c5bc769a898c206a1c6a4f9
use_hf_model_config: true
hf_save_steps: 328
hf_save_path: /e/fscratch/reformo/lee27/checkpoints/ota10k_sft_30ba3b_levanter/hf
